Repository AY2122S1-CS2103T-F12-2/tp, pull requests merged in 2021-11, with the labels that each got.

#208 Update UG
  docs/UserGuide.md
Labels: type.documentation

#162 Update UML sequence diagrams for Filter Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterSequenceDiagram.puml
  docs/images/filter/FilterSequenceDiagram.png
  src/main/java/seedu/intern/model/applicant/GraduationYearMonth.java
  src/main/java/seedu/intern/ui/PersonDetailPanel.java
Labels: type.Enhancement, type.documentation

#205 Add boundary for GraduationMonthYear field.
  docs/UserGuide.md
  src/main/java/seedu/intern/model/applicant/GraduationYearMonth.java
  src/test/java/seedu/intern/model/applicant/GraduationYearMonthTest.java
Labels: type.Bug

#210 Fix UG description + UML
  docs/UserGuide.md
  docs/diagrams/DeleteAllSequence.puml
Labels: type.Bug, severity.Medium

#222 Fix bugs for:
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/intern/logic/commands/FilterCommand.java
  src/main/java/seedu/intern/model/applicant/Name.java
  src/test/java/seedu/intern/model/applicant/ApplicantTest.java
Labels: type.Enhancement, type.Bug, priority.Medium, severity.Medium

#207 Fix Application Status colour regression, update UG/PlantUML/PPP, fix Select bug
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditAllSequence.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/team/chang-ch.md
  src/main/java/seedu/intern/model/applicant/ApplicationStatus.java
  src/main/java/seedu/intern/ui/MainWindow.java
  src/main/java/seedu/intern/ui/PersonDetailPanel.java
  src/main/java/seedu/intern/ui/PersonListPanel.java
Labels: type.Bug, severity.Medium, severity.Low, type.documentation

#226 Add PPP for Gu Geng and change filtercommand description.
  docs/team/jackgugz.md
  src/main/java/seedu/intern/logic/commands/FilterCommand.java
Labels: type.documentation

#227 V1.4 ppp
  docs/AboutUs.md
Labels: type.documentation

#238 Add code reuse credits and update design consideration for undo/redo
  docs/DeveloperGuide.md
  docs/team/jeromesyl.md
  src/main/java/seedu/intern/model/VersionedInternWatcher.java
Labels: type.documentation

#253 Update DG bugs
  docs/DeveloperGuide.md
Labels: type.documentation

#254 UG update
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.documentation

#257 Update Roles, Responsibilities and features for all
  docs/AboutUs.md
  docs/team/jackgugz.md
Labels: type.Enhancement, type.documentation

#258 Trial UG/DG width fix
  docs/_sass/custom/_base.scss
Labels: type.documentation

#267 Improve code quality, fix AboutUs attribution
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/chang-ch.png
  docs/team/chang-ch.md
  docs/team/yunpeng1234.md
  src/main/java/seedu/intern/commons/core/selection/Selection.java
  src/main/java/seedu/intern/logic/parser/ParserUtil.java
  src/test/java/seedu/intern/logic/parser/ParserUtilTest.java
Labels: type.Task, type.documentation

#270 Update UserGuide to highlight invalid
  docs/UserGuide.md
Labels: type.Bug, priority.Low, type.documentation

#269 Fix read only, view state bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/intern/logic/LogicManager.java
Labels: type.Bug, severity.Low

#283 Update UG
  docs/UserGuide.md
Labels: severity.High

#284 Update DG
  docs/DeveloperGuide.md
Labels: priority.Medium
