Repository AY2122S1-CS2103T-F12-2/tp, pull requests merged in 2021-10, with the labels that each got.

#54 Remove address field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Low

#62 Update AbousUs and UserGuide documentation.
  docs/AboutUs.md
  docs/UserGuide.md
Labels: type.Task

#85 Add editAll feature
  src/main/java/seedu/intern/logic/commands/EditAllCommand.java
  src/main/java/seedu/intern/logic/commands/EditCommand.java
  src/main/java/seedu/intern/logic/parser/EditAllCommandParser.java
  src/main/java/seedu/intern/logic/parser/InternWatcherParser.java
  src/test/data/JsonSerializableInternWatcherTest/typicalPersonsInternWatcher.json
  src/test/java/seedu/intern/logic/commands/CommandTestUtil.java
  src/test/java/seedu/intern/logic/commands/EditAllCommandTest.java
  src/test/java/seedu/intern/logic/parser/EditAllCommandParserTest.java
  src/test/java/seedu/intern/testutil/ApplicantBuilder.java
  src/test/java/seedu/intern/testutil/ApplicantUtil.java
  src/test/java/seedu/intern/testutil/EditAllDescriptorBuilder.java
  src/test/java/seedu/intern/testutil/EditApplicantDescriptorBuilder.java
  src/test/java/seedu/intern/testutil/TypicalApplicants.java
Labels: type.Story, type.Enhancement, priority.Medium

#94 Rework Delete command with new Selection Class
  src/main/java/seedu/intern/commons/core/selection/Selection.java
  src/main/java/seedu/intern/logic/commands/DeleteCommand.java
  src/main/java/seedu/intern/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/intern/commons/core/selection/SelectionTest.java
  src/test/java/seedu/intern/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/intern/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/intern/logic/parser/InternWatcherParserTest.java
  src/test/java/seedu/intern/logic/parser/ParserUtilTest.java
  src/test/java/seedu/intern/testutil/TypicalIndexes.java
  src/test/java/seedu/intern/testutil/TypicalSelections.java
Labels: type.Story, priority.Medium

#107 Add filter command test cases
  src/main/java/seedu/intern/logic/commands/FilterCommand.java
  src/main/java/seedu/intern/logic/parser/FilterCommandParser.java
  src/main/java/seedu/intern/model/applicant/CombineFiltersPredicate.java
  src/test/data/JsonSerializableInternWatcherTest/typicalPersonsInternWatcher.json
  src/test/java/seedu/intern/logic/commands/FilterCommandTest.java
  src/test/java/seedu/intern/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/intern/testutil/FilterApplicantDescriptorBuilder.java
  src/test/java/seedu/intern/testutil/TypicalApplicants.java
Labels: type.Enhancement, priority.High, hacktoberfest-accepted

#179 Fix PE-D bug for Grade Class
  src/main/java/seedu/intern/model/applicant/Grade.java
  src/test/java/seedu/intern/model/applicant/GradeTest.java
Labels: type.Bug

#181 Fix PE-D UG Issues
  docs/UserGuide.md
Labels: type.documentation

#193 Fix UG text errors
  docs/UserGuide.md
Labels: priority.Medium, type.documentation

#204 Fix pe-d bug for Course and Job.
  src/main/java/seedu/intern/model/applicant/Course.java
  src/main/java/seedu/intern/model/applicant/Job.java
  src/test/java/seedu/intern/model/applicant/CourseTest.java
Labels: type.Bug

#206 Update UserGuide.md
  docs/UserGuide.md
Labels: type.documentation
